# Generated by Django 4.1.1 on 2024-04-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='images/logo.jpg', upload_to='images/'),
        ),
    ]
