# Generated by Django 4.1.1 on 2024-04-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='/Users/ripabiswas/GitHub Folders/fpc/images/logo.png', upload_to='images/'),
        ),
    ]
