# Generated by Django 4.1.1 on 2024-04-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='media/images/logo.png', upload_to='media/images/'),
        ),
    ]
