# Generated by Django 4.1.1 on 2024-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('member_image', models.ImageField(default='committee/images/logo.png', upload_to='committee/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='media/images/logo.png', upload_to='news/images/'),
        ),
    ]
